### ISSUE TITLE
Main Page / feed.html

### ISSUE THREAD

**Issue by Xurya** [TracyZheng22/CSE312#5]
Create a template feed front end for the main page. Since this is a larger assignment, reattaching idea document below:

![image.png](https://images.zenhubusercontent.com/5e64204f1fa19e0ae6659c81/c138393a-1d26-4fd0-8289-e335c4c50b84)

**Comment by Xurya** [comment]
Need more work to be done, add more assignees

**Comment by Lunicks** [comment]
Set for now. Will need future rework.
